on:
  push:
    branches:
     - main
name: Push to CodeHub
jobs:
  push_to_bitbucket:
    name: Push to CodeHub
    if: "!github.event.deleted"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0 # Zero indicates all history
        ref: main
    - name: Push to mirror
      uses: reload/git-push-mirror-action@main
      with:
        args: https://${{ secrets.CODEHUB_USER }}:${{ secrets.CODEHUB_PASSWORD }}@codehub.devcloud.huaweicloud.com/scrum-demo00006/repo_for_mirror.git
