on:
  push:
    branches:
    - '**'
name: Push to CodeHub
jobs:
  push_to_codehub:
    name: Push to CodeHub
    if: "!github.event.deleted"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0 # Zero indicates all history
        ref: main
    - name: Push to mirror
      run: |
        git fetch -pu origin +refs/*:refs/*
        git push --mirror -f https://${{ secrets.CODEHUB_USER }}:${{ secrets.CODEHUB_PASSWORD }}@codehub.devcloud.huaweicloud.com/scrum-demo00006/repo_for_mirror.git
      
